FROM ubuntu:latest

RUN apt-get update -y && apt-get install -y python3 python3-pip libpcre3 libpcre3-dev

COPY app /app/
WORKDIR /app/
RUN pip3 install -r requirements.txt

EXPOSE 5555

ENV FLASK_APP=app.py
ENV FLASK_ENV=development
CMD ["uwsgi", "--http", ":5555", "--module", "app:app", "--master", "--processes", "4", "--threads", "2", "--stats", "0.0.0.0:9191"]
