#!/usr/bin/bash

psql -d
postgresql://$IG_USER:$IG_PASSWD@$PG_HOST:$PG_PORT/$IG_DATABASE
CREATE TABLE users (username VARCHAR(50), password VARCHAR(50), full_name VARCHAR(50));
INSERT INTO users (dongji, cpsc4973, dongji grader);