#!/usr/bin/bash

psql -h ${PG_HOST} -d ${IG_DATABASE} -u ${IG_USER} << EOF
CREATE TABLE users (username VARCHAR(50), password VARCHAR(50), full_name VARCHAR(50));
INSERT INTO users (dongji, cpsc4973, dongji grader);
EOF
